version: '3'
services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.25.0-focal
    shm_size: 1gb
    ipc: host
    cap_add:
      - SYS_ADMIN
    networks:
      - backend
    environment:
      - INTEGRATION_TESTS_BRANCH
      - MAGENTO_BASE_URL
      - MAGENTO_ADMIN_USERNAME
      - MAGENTO_ADMIN_PASSWORD
      - PAYPAL_USERNAME
      - PAYPAL_PASSWORD
      - ADYEN_MERCHANT
      - ADYEN_CLIENT_KEY
      - ADYEN_API_KEY
    volumes:
      - ../../scripts/e2e.sh:/e2e.sh
      - ../../../test-report:/tmp/projects/test-report