name: Magento E2E Headless Tests with Playwright
run-name: Headless E2E tests for ${{ github.event.pull_request.head.ref}}

on:
  pull_request:
    paths-ignore:
      - "shopware/**"
    branches: [main, develop]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'renovate[bot]' || github.actor != 'lgtm-com[bot]' }}
    env:
      GITHUB_TOKEN: ${{ secrets.ADYEN_AUTOMATION_BOT_TEST_ACCESS_TOKEN }}
    steps:
      - name: Run E2E Tests
        run: gh workflow run test-repo-e2e.yml -R Adyen/adyen-magento2 -F testBranch=${{ github.event.pull_request.head.ref}}
