name: Magento E2E Headless Tests with Playwright
run-name: Headless E2E tests for ${{ github.event.pull_request.head.ref}}

on:
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.TEST_TOKEN }}
    steps:
      - name: Run E2E Tests
        run: gh workflow run e2e.yml -R Adyen/adyen-magento2 -F testBranch=${{ github.event.pull_request.head.ref}}
