name: Magento E2E Headless Tests with Playwright
on:
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ADYEN_AUTOMATION_BOT_ACCESS_TOKEN }}
      TEST_BRANCH: ${{ github.event.pull_request.head.ref}}
    steps:
      - name: Run E2E Tests
        run: gh workflow run e2e-only.yml -R Adyen/adyen-magento2
